thedirectory/accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
]

thedirectory/agency/urls.py
from django.urls import path
from . import views

app_name = 'agency'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('search',views.search, name = 'search' ),
    path('<int:agency_id>/',views.agency_detail, name = 'agency_detail' ),

]

thedirectory/thedirectory/urls.py
from django.contrib import admin
from django.urls import include,path 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
# from . import views

urlpatterns = [
    path('agency/', include('agency.urls')),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('registration.backends.hmac.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

thedirectory/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
# class User(AbstractUser):
#     is_agencyadmin = models.BooleanField(default=False)
#     is_agent = models.BooleanField(default=False)
#     is_client = models.BooleanField(default=False)
    
    

thedirectory/agency/models.py
from django.db import models

# Create your models here.

class Agency(models.Model):
    agencyname = models.CharField(max_length = 200)
    registration_no = models.IntegerField()
    agency_logo = models.ImageField(default='default.jpg')

    def __str__(self):
        return self.agencyname

    class Meta:
        ordering = ['agencyname']

    @classmethod
    def search_by_name(cls,search_term):
        agency = cls.objects.filter(agenncyname__icontains=search_term)
        return agency

class Agent(models.Model):
    name = models.CharField(max_length = 100)
    agency = models.ForeignKey(Agency,on_delete=models.CASCADE,blank =True)
    registration_no = models.IntegerField()
    email = models.EmailField()
    phone_no = models.IntegerField()

thedirectory/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

# from .models import User, AgencyAdmin

# class AgencyAdminForm(UserCreationForm):
#     name = forms.TimeField()
#     email = 


class alertletterForm(forms.Form):
    your_name = forms.CharField(label='First Name', max_length=30)
    email = forms.EmailField(label='Email')

thedirectory/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from .forms import alertletterForm

# from .models import User
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if  form.is_valid():
            form.save()
            return redirect('agency:index')
    else:
        form=UserCreationForm()
            
    return render(request, 'registration/signup.html', {'form':form})

# def AgencyAdminSgnupView(CreateView):
#     model = User
#     form = AgencyAdminSgnupForm
#     template = 'registration/register.html'

#     def get_context_data(self, **kwargs):
#         kwargs['user_type'] = 'student'
#         return super().get_context_data(**kwargs)

#     def form_valid(self, form):
#         user = form.save()
#         login(self.request, user)
#         return redirect('agency:index')

#     pass

def sendalert(request):
    if request.method =='POST':
        form = alertletterForm(request.POST)
        if form.is_valid():
            print('valid')
        else:
            form = alertletterForm()
        return render(request, 'index.html', form)

thedirectory/agency/views.py
from django.shortcuts import get_object_or_404, render
from .models import Agency, Agent
from django.http import HttpResponse,Http404

# Create your views here.
def index(request):
    all_agencies = Agency.objects.all()
    # context = {'all_agencies':all_agencies}  
    return render(request, 'index.html', locals())

def agency_detail(request, agency_id):

    try:
        agency = Agency.objects.get(pk = agency_id)
    except Agency.DoesNotExist:
        raise Http404()
        # context = {'agency':agency}
    return render(request, 'agencies/agency.html',{'agency':agency,})

def search(request):
    if 'agency' in request.GET and request.GET["agency"]:
        search_term = request.GET.get('agency')
        searched_agencies = Agency.search_by_name(search_term)
        message = f'{ search_term}'
        return render(request, 'search.html',{"message":message,"agencies":searched_agencies})
    else:
        message = 'We can\'t find any results ${message}'
        return render(request, 'agencies/search.html', locals())

thedirectory/agency/templates/agencies/agency.html
{% extends 'base.html'%}
{% block content %}
<div class="row">
    
    <!-- agency brief -->
    <div class="col-md-12">
        <h1>{{agency.agencyname}}</h1>
            <div class="col-md-8">
                    <section>
                            <div class="py-3">
                              <div class="card">
                                <div class="row ">
                                  <div class="col-md-4">
                                      <img src="{{agency.agency_logo.url}}" class="w-100">
                                    </div>
                                    <div class="col-md-8 px-3">
                                      <div class="card-block px-3">
                                        <h4 class="card-title">Lorem ipsum dolor sit amet</h4>
                                        <p class="card-text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                                        <p class="card-text">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                        <a href="#" class="btn btn-primary">Read More</a>
                                      </div>
                                    </div>
                          
                                  </div>
                                </div>
                              </div>
                          </section>
        
        
        
            <!-- featured properties -->
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title"> <a href="">{{agency.agencyname}}</a> </h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="card-link">View Properties</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title"> <a href="">{{agency.agencyname}}</a> </h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="card-link">View Properties</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title"> <a href="">{{agency.agencyname}}</a> </h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="card-link">View Properties</a>
                        </div>
                    </div>
                </div>
        
            </div>
            <!-- properties list -->
            <div class="col-md-4">
                
                    <div class="card card-image" style="background-image: url({{agency.agency_logo.url}});">

                            <!-- Content -->
                            <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
                            <div>
                                <h5 class="pink-text"><i class="fas fa-chart-pie"></i> Marketing</h5>
                                <h3 class="card-title pt-2"><strong>This is the card title</strong></h3>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat fugiat, laboriosam, voluptatem,
                                optio vero odio nam sit officia accusamus minus error nisi architecto nulla ipsum dignissimos.
                                Odit sed qui, dolorum!.</p>
                                <a class="btn btn-pink"><i class="fas fa-clone left"></i> {{agency.agencyname}}</a>
                            </div>
                            </div>
                        
                        </div>
                    <div class="card card-image" style="background-image: url({{agency.agency_logo.url}});">

                            <!-- Content -->
                            <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
                            <div>
                                <h5 class="pink-text"><i class="fas fa-chart-pie"></i> Marketing</h5>
                                <h3 class="card-title pt-2"><strong>This is the card title</strong></h3>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat fugiat, laboriosam, voluptatem,
                                optio vero odio nam sit officia accusamus minus error nisi architecto nulla ipsum dignissimos.
                                Odit sed qui, dolorum!.</p>
                                <a class="btn btn-pink"><i class="fas fa-clone left"></i> {{agency.agencyname}}</a>
                            </div>
                            </div>
                        
                        </div>
                    <!-- Card -->
                    <div class="card card-image" style="background-image: url({{agency.agency_logo.url}});">

                        <!-- Content -->
                        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
                        <div>
                            <h5 class="pink-text"><i class="fas fa-chart-pie"></i> Marketing</h5>
                            <h3 class="card-title pt-2"><strong>This is the card title</strong></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat fugiat, laboriosam, voluptatem,
                            optio vero odio nam sit officia accusamus minus error nisi architecto nulla ipsum dignissimos.
                            Odit sed qui, dolorum!.</p>
                            <a class="btn btn-pink"><i class="fas fa-clone left"></i> {{agency.agencyname}}</a>
                        </div>
                        </div>
                    
                    </div>
                    <!-- Card -->
                
        
            </div>
        
        </div>

    </div>
    
{% endblock %}

thedirectory/agency/templates/agencies/search.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        {%if agencies%}
            <h2>Found {{ agencies|length }} of searched term {{message}}</h2>
        {% else %}
            <h2> Found 0 agencies for the search term {{message}}</h2>
        {% endif %}

    </div>
    <div class="row">
        {%if agencies%}
            {%for agency in agencies%}
            <div class="col-sm-6 col-md-3">
                <h1>{{agency.agencyname}}</h1>
            </div>
            {% endfor%}
        {% endif %}
    </div>

</div>
{%endblock%}

thedirectory/agency/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
    <!-- bootsnipp -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <link href="https://fonts.googleapis.com/css?family=Slabo+27px&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/styles.css">
    
    {% if title %}
    <title>The Directory - {{title}}</title>
    {% else %}
        <title> The Directory </title>
    {% endif %}

    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
</head>
<body>
    {%include 'navbar.html'%}
    
    <div class="container">
            
        <div class="row">
            
            <div class="col-md-12">
                
                {% block content %}
                {% endblock %}
            </div>
        </div>

    </div>



    


    {% block scripts%}
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>  
    <script type="text/javascript" src="js/mdb.min.js"></script>   
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    {% endblock%}
</body>
</html>

thedirectory/agency/templates/index.html
{% extends 'base.html'%}
{% load static%}

<h1>THE DIRECTORY</h1>
{% block content%}
<h5>Welcome  {% if user.is_authenticated%} {{user.username }} {% else %} visitor {% endif %}</h5>

{% for agency in all_agencies %}

    <!-- Card -->
    <div class="col-md-4">
            <div class="card">
                <!-- Card image -->
                    <div class="view overlay">
                      <img class="card-img-top" src="{{agency.agency_logo.url}}" alt="Card image cap">
                      <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                      </a>
                    </div>
                  
                    <!-- Card content -->
                    <div class="col-md-4">
                        
                    </div>
                    <div class="card-body">
                  
                      <!-- Title -->
                      <h4 class="card-title"> <a href="{{agency.id}}">{{agency.agencyname}}</a></h4>
                      <!-- Text -->
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <!-- Button -->
                      <a href="#" class="btn btn-primary">View Properties</a>
                  
                    </div>

    </div>

  
  </div>
  <!-- Card -->
{% endfor%}

{% endblock%}

thedirectory/agency/templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg  ">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="{% url 'agency:index' %}">The Directory</a>

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      {%if user.is_authenticated%}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout'%}">Log Out</a>
      </li>
      {% else %}
      <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup'%}">Sign Up</a>
          </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login'%}">Log In</a>
      </li>
      {% endif %}


      <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
    <!-- Links -->

    <form class="form-inline" role="search" action="{% url 'agency:search' %}">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search Agency" aria-label="Search">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->